name: Deploy Angular App to Azure Web App

on:
  workflow_run:
    workflows: ["Build and Test Angular App"]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: testsampleangular 

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: angular-build
          path: dist/login-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: dist/login-app
